import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.scss";
import ClientSideWrapper from "@/lib/wapper";
import Layout from "@/components/layout/Layout";

const inter = IBM_Plex_Sans({
  subsets: ["latin"],
  preload: true,
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Word Wave",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientSideWrapper>{children}</ClientSideWrapper>
      </body>
    </html>
  );
}
